apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: find
spec:
  version: v0.3.0
  homepage: https://github.com/alikhil/kubectl-find
  shortDescription: Find resources and perform action on them.
  description: |
    It's a plugin for kubectl that gives you a UNIX find-like experience.
    Find then print, patch or delete any resource matching the provided criteria based on name, age, labels, etc
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.3.0/kubectl-find_Linux_x86_64.tar.gz
    sha256: 57f0e3305bdfce511dbfbf495ba503ac5998d5b69886364a5e719e315e6baabb
    bin: kubectl-find
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.3.0/kubectl-find_Linux_arm64.tar.gz
    sha256: e8e6c143b7bb812bd837a73590387ee50a914275614bbaed30fc310acbe69dc8
    bin: kubectl-find
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.3.0/kubectl-find_Darwin_x86_64.tar.gz
    sha256: c0e264cc29684e4be0c66ecba81e0348e99440eb22094677a161c494f3eead77
    bin: kubectl-find
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.3.0/kubectl-find_Darwin_arm64.tar.gz
    sha256: 177fb17fe500fc627de8de7aa9e0d8d057fdfbe689a52685fd5e609a4caa907d
    bin: kubectl-find
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.3.0/kubectl-find_Windows_x86_64.zip
    sha256: 1e6e4b28e8ae5285ff37fa62d1a3f710d591009d95a681994de78db50a28bccf
    bin: kubectl-find.exe
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.3.0/kubectl-find_Windows_arm64.zip
    sha256: 3eb13a4b0c18ef0c446600180bd272e0cb36c0a42c8945ce389331c4d35200a9
    bin: kubectl-find.exe
