apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: find
spec:
  version: v0.1.0
  homepage: https://github.com/alikhil/kubectl-find
  shortDescription: Find resources and perform action on them.
  description: |
    It's a plugin for kubectl that gives you a UNIX find-like experience.
    Find then print, patch or delete any resource matching the provided criteria based on name, age, labels, etc
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.1.0/kubectl-find_Linux_x86_64.tar.gz
    sha256: 3fab6f6e20e17332d89f158d42837f7ea4d64f1c0e68bd9f582f98bb885176a3
    bin: kubectl-find
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.1.0/kubectl-find_Linux_arm64.tar.gz
    sha256: c87a73b01f6a91e671d7d4d0ed0e43f90015036ca137e25455231c53d50c3520
    bin: kubectl-find
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.1.0/kubectl-find_Darwin_x86_64.tar.gz
    sha256: e0da110188f904cdc7ad90abcb2c397305be979a01373e8051ab38a54cbc4599
    bin: kubectl-find
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.1.0/kubectl-find_Darwin_arm64.tar.gz
    sha256: 942abe5a59d6c8a75d907517450313533a94a4b27511f2d5cbd0ae59fdb7a5de
    bin: kubectl-find
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.1.0/kubectl-find_Windows_x86_64.zip
    sha256: daa3bbe8578385093905f3e2dfa45eeeeedfe545ed2e4d852f5d9fd7eb3a2569
    bin: kubectl-find.exe
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.1.0/kubectl-find_Windows_arm64.zip
    sha256: 38aff43f196ed87a79ab9be00f7427361f5f159f1e4779b41d2b31d44a994bdc
    bin: kubectl-find.exe