apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: find
spec:
  version: v0.2.1
  homepage: https://github.com/alikhil/kubectl-find
  shortDescription: Find resources and perform action on them.
  description: |
    It's a plugin for kubectl that gives you a UNIX find-like experience.
    Find then print, patch or delete any resource matching the provided criteria based on name, age, labels, etc
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.2.1/kubectl-find_Linux_x86_64.tar.gz
    sha256: 38aecd425a8483514cfa4894f4b313b2bdbe488d8ad7228fa63b1ebb998f0ed3
    bin: kubectl-find
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.2.1/kubectl-find_Linux_arm64.tar.gz
    sha256: 35aacc29905873650d6612c963767b3450f7fdf6b718f1c629ff6da45160fcb8
    bin: kubectl-find
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.2.1/kubectl-find_Darwin_x86_64.tar.gz
    sha256: 34ea6f548f8f323f53d92054f3bbc3dddc15df741ef1ef2013dce3fea9719990
    bin: kubectl-find
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.2.1/kubectl-find_Darwin_arm64.tar.gz
    sha256: 464b81e3acfbd9acea5ff1e4ecd2b9f958f505b5bedf782b122b9a137a18824d
    bin: kubectl-find
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.2.1/kubectl-find_Windows_x86_64.zip
    sha256: 92f03858fdf7b88b5c21a2fff6bb75977159226d8ae97956e5e881e0f9cc0b07
    bin: kubectl-find.exe
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.2.1/kubectl-find_Windows_arm64.zip
    sha256: fb75a66e8085e2d6876713e3702e61ef68be9e9d286bf6a444f37151bb53f25a
    bin: kubectl-find.exe
