apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: find
spec:
  version: v0.2.0
  homepage: https://github.com/alikhil/kubectl-find
  shortDescription: Find resources and perform action on them.
  description: |
    It's a plugin for kubectl that gives you a UNIX find-like experience.
    Find then print, patch or delete any resource matching the provided criteria based on name, age, labels, etc
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.2.0/kubectl-find_Linux_x86_64.tar.gz
    sha256: 06d290dd6d1e353b9d3048e5d032baa0bc2f931b6c2e9647faaff9959ace71c8
    bin: kubectl-find
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.2.0/kubectl-find_Linux_arm64.tar.gz
    sha256: f6c5ef7e9eded74d18ebb18b1b74f4fd4d530ef901320a1131384bd09ac1b8e9
    bin: kubectl-find
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.2.0/kubectl-find_Darwin_x86_64.tar.gz
    sha256: 98c56142a539ca518d729a216e488fd2d3dd2bc649fbd1bb5ce1c93ceec16cb0
    bin: kubectl-find
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.2.0/kubectl-find_Darwin_arm64.tar.gz
    sha256: fc43258a168689bcc369fb498fef76c7836d48798da013b16913f7294ac12a86
    bin: kubectl-find
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.2.0/kubectl-find_Windows_x86_64.zip
    sha256: 8bd5712a11112c279b1b5561c6b2139b7257201e13edd0c02ec406c1880b44ee
    bin: kubectl-find.exe
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    uri: https://github.com/alikhil/kubectl-find/releases/download/v0.2.0/kubectl-find_Windows_arm64.zip
    sha256: 4ad7edaecc2ceb87e9be8f5a7a16b6a5d91874100c1ca3ec5164af7a5edcd42f
    bin: kubectl-find.exe
